training:
  seed: 42
  num_epochs: 40
  batch_size: 16
  optimizer:
    type: "adamw"
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    type: "cosine_annealing"
    T_max: 40
  grad_clip:
    enabled: True
    max_norm: 1.0
  label_smoothing: 0.1
  log_every: 50
  save_every: 5
  eval_recall_every: 10
  checkpoint_dir: "/home/erzurumlu.1/yunus/research_drive/checkpoints"

accelerate:
  fp16: true
  logging_dir: "logs"  # Directory for Accelerate to store logs
  
dataset:
  name: "VIGOR"
  data_folder: "/home/erzurumlu.1/yunus/research_drive/data/VIGOR"
  same_area: true
  batch_size: 16
  num_workers: 4
  ground_transforms:
    - type: "Resize"
      height: 384
      width: 768
    - type: "ToTensor"
  satellite_transforms:
    - type: "Resize"
      height: 384
      width: 384
    - type: "ToTensor"

wandb:
  enabled: true
  project: "glip-loc"
  entity: "erzurumlu-1-the-ohio-state-university"

accelerate:
  enabled: true
  fp16: true

model:
  name: "convnext_base"
  pretrained: true
  use_text: false
