training:
  seed: 42
  num_epochs: 400
  batch_size: 16
  optimizer:
    type: "adamw"
    lr: 0.01
    weight_decay: 0.01
  # scheduler:
  #   type: "null" # cosine_annealing
  #   T_max: 40
  # grad_clip:
  #   enabled: False
  #   max_norm: 100.0
  label_smoothing: 0.1
  log_every: 50
  save_every: 500
  eval_recall_every: 10
  checkpoint_dir: "/home/erzurumlu.1/yunus/research_drive/checkpoints"

accelerate:
  fp16: false
  logging_dir: "logs"  # Directory for Accelerate to store logs

dataset:
  name: "VIGOR"
  data_folder: "/home/erzurumlu.1/yunus/research_drive/data/VIGOR"
  same_area: false
  batch_size: 4
  num_workers: 0
  ground_transforms:
    - type: "Resize"
      height: 224
      width: 224
    - type: "ToTensor"
  satellite_transforms:
    - type: "Resize"
      height: 224
      width: 224
    - type: "ToTensor"

wandb:
  enabled: false
  project: "glip-loc"
  entity: "erzurumlu-1-the-ohio-state-university"

accelerate:
  enabled: true
  fp16: False

model:
  name: "openai/clip-vit-base-patch16"
  pretrained: true
  use_text: false
